### ISSUE TITLE
Disable/Enable Click

### ISSUE THREAD

**Issue by shannonj498** [shannonj498/memory-matching-game#1]
Currently, users are able to click on the same card twice which returns a match. I am able to disable clicks after the card is open but having trouble enabling clicks if the cards don't match. The file can be viewed in js/app.js

**Comment by freginold** [comment]
One way you could do it is to just `return` if a click was logged on a card that's already face up.  Adding this line to `findMatch()` just inside the click handler should do the trick:

    if ($(this).hasClass("open show")) { return; }

That way, you don't have to worry about disabling and re-enabling the click handler.
